// Prepends the project's own "do not edit" banner to the freshly generated
// src/api.ts, on top of openapi-typescript's own default header. Run as the
// last step of `npm run codegen` (see package.json) — never by hand.
import { readFileSync, writeFileSync } from "node:fs";

const target = new URL("../src/api.ts", import.meta.url);

const banner = `// GENERATED by \`npm run codegen\` from the backend's OpenAPI schema.
// Do not edit. Change the Pydantic model and regenerate.

`;

const contents = readFileSync(target, "utf8");
if (!contents.startsWith(banner)) {
  writeFileSync(target, banner + contents);
}
