// GENERATED by `npm run codegen` from the backend's OpenAPI schema.
// Do not edit. Change the Pydantic model and regenerate.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Content */
        get: operations["content_api_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run */
        get: operations["read_run_api_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile
         * @description The run so far: who it is for, how far in, what he has answered and won.
         *
         *     `answered` is built ONLY from `cleared_segments`. A question he has not
         *     cleared contributes nothing, so there is no path here that hands him an
         *     answer he has not already produced himself.
         */
        get: operations["profile_api_run_profile_get"];
        put?: never;
        /** Run Profile Chosen */
        post: operations["run_profile_chosen_api_run_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate */
        post: operations["activate_api_run_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/installed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Installed */
        post: operations["run_installed_api_run_installed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/howto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Howto Acked */
        post: operations["run_howto_acked_api_run_howto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/difficulty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose Difficulty */
        post: operations["choose_difficulty_api_run_difficulty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/segment/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Segment */
        post: operations["start_segment_api_run_segment_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/segment/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Game */
        post: operations["submit_game_api_run_segment_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/segment/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submit_answer_api_run_segment_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checkpoint */
        post: operations["submit_checkpoint_api_run_checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Release */
        post: operations["approve_release_api_operator_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/toast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Toast */
        post: operations["send_toast_api_operator_toast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/unlock-gate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock Gate */
        post: operations["unlock_gate_api_operator_unlock_gate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/pass-checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bypass Checkpoint
         * @description Pass a checkpoint WITHOUT the passphrase, and release its reward.
         *
         *     THE ONE ROUTE THAT DEFEATS THE GATE ON PURPOSE. Everything else in this
         *     system exists to make sure a gift-card code cannot be obtained without
         *     the out-of-band phrase only the operator holds; this hands it over on a
         *     click. That is the point: on the night, the failure that actually costs
         *     something is not "someone cheated the gate", it is "the gate broke, or
         *     he cannot type the phrase, and the present does not arrive". The gate
         *     protects a code the operator is going to read aloud anyway, over a call,
         *     to the one person it is for.
         *
         *     It is safe to reach for because it is not privileged beyond what the
         *     operator can already do: this router is behind `require_operator`, and
         *     an operator can already emit any code directly via `/approve`. This
         *     route adds no new power -- it makes the run's STATE agree with what the
         *     operator was always able to do to the vault, which `/approve` alone does
         *     not (that is precisely how the run observed live ended up holding a
         *     released reward while still sitting on the checkpoint screen).
         *
         *     Runs the same `RunService.pass_checkpoint` the real code path runs, so
         *     the rescue cannot drift from the thing it is rescuing. The only
         *     difference it makes is a `bypassed_by_operator` marker on the audit log.
         */
        post: operations["bypass_checkpoint_api_operator_pass_checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/skip-game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Game
         * @description Clear the current game without playing it, and go to its question.
         *
         *     The rescue for a game that will not cooperate -- a mechanic misbehaving,
         *     a keyboard that is not registering, or simply a segment he cannot get
         *     past while everyone waits. It counts as a pass, so the game trophy is
         *     awarded exactly as if he had played it: from the run's point of view the
         *     segment's skill half is done, and the question still has to be answered
         *     on his own.
         *
         *     Much narrower than the checkpoint bypass: no gift card is released and
         *     no gate is defeated, so it is a single click with no typed confirmation.
         */
        post: operations["skip_game_api_operator_skip_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/reset-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Run
         * @description Put a run back to its very first screen. FOR TESTING.
         *
         *     Deletes every trophy, gate attempt, consumed token, event AND released
         *     code for the run, then resets the row. It exists because testing the
         *     night end to end otherwise means hand-editing the database, which is how
         *     this project twice hit a foreign-key violation by deleting in the wrong
         *     order.
         *
         *     WHAT MAKES THIS DIFFERENT FROM EVERY OTHER OPERATOR ACTION:
         *     `code_releases` is the only thing enforcing that a gift card is released
         *     at most once (`VaultService.release` leans on its
         *     UNIQUE(run_id, reward_id)). Clearing it makes an already-given code
         *     releasable again -- exactly what a test rerun needs, and exactly what
         *     must never happen by accident on the night. Hence the typed
         *     confirmation, and hence a response reporting what was destroyed rather
         *     than a bare {"ok": true}.
         */
        post: operations["reset_run_api_operator_reset_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/force-golive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force Golive */
        post: operations["force_golive_api_operator_force_golive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operator State */
        get: operations["operator_state_api_operator_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivateRequest */
        ActivateRequest: {
            /** Code */
            code: string;
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** Answer */
            answer: string;
        };
        /** AnswerResponse */
        AnswerResponse: {
            /** Phase */
            phase: string;
            /** Segment */
            segment: number;
            /** Difficulty */
            difficulty: string | null;
            /** Cleared Segments */
            cleared_segments: number[];
            /** Released Rewards */
            released_rewards: number[];
            /** Lives */
            lives: number | null;
            /** Question Attempts Left */
            question_attempts_left: number | null;
            /** Trophies */
            trophies: string[];
            question: components["schemas"]["QuestionView"] | null;
            /** Passed */
            passed: boolean;
            /**
             * Retry
             * @default false
             */
            retry: boolean;
            /** Roast */
            roast?: string | null;
        };
        /**
         * AnsweredView
         * @description One question he has already got right.
         *
         *     Only ever built for a CLEARED segment. The answer key never reaches the
         *     client for anything still ahead of him — same rule QuestionView follows
         *     by omitting `accept` — so this can reveal nothing he has not already
         *     earned.
         */
        AnsweredView: {
            /** Segment */
            segment: number;
            /** Prompt */
            prompt: string;
            /** Answer */
            answer: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /** Run Id */
            run_id: number;
            /** Reward Id */
            reward_id: number;
        };
        /** BypassCheckpointRequest */
        BypassCheckpointRequest: {
            /** Run Id */
            run_id: number;
        };
        /** BypassCheckpointResponse */
        BypassCheckpointResponse: {
            /** Phase */
            phase: string;
            /** Segment */
            segment: number;
            released: components["schemas"]["CodeReleasedMsg"] | null;
        };
        /** CheckpointRequest */
        CheckpointRequest: {
            /** Code */
            code: string;
        };
        /** CheckpointResponse */
        CheckpointResponse: {
            /** Outcome */
            outcome: string;
            /** Attempts Remaining */
            attempts_remaining: number | null;
            released: components["schemas"]["CodeReleasedMsg"] | null;
            run: components["schemas"]["RunView"];
        };
        /** CodeReleasedMsg */
        CodeReleasedMsg: {
            /**
             * Type
             * @default code_released
             * @constant
             */
            type: "code_released";
            /** Reward Id */
            reward_id: number;
            /** Label */
            label: string;
            /** Code */
            code: string;
        };
        /** ContentView */
        ContentView: {
            copy: components["schemas"]["CopyView"];
            /** Trophies */
            trophies: components["schemas"]["TrophyView"][];
        };
        /** CopyView */
        CopyView: {
            /** Coming Soon */
            coming_soon: string;
            /** Teaser */
            teaser: string;
            /** How To Play */
            how_to_play: string;
            /** Closing */
            closing: string;
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "kiddie" | "devil";
        /** DifficultyRequest */
        DifficultyRequest: {
            difficulty: components["schemas"]["Difficulty"];
        };
        /** GameResultBody */
        GameResultBody: {
            /** Mechanic */
            mechanic: string;
            /** Passed Client Side */
            passed_client_side: boolean;
            /** Duration Ms */
            duration_ms: number;
            /** Input Count */
            input_count: number;
            /** Score */
            score: number;
            /** Sequence */
            sequence?: number[];
        };
        /** GameSubmission */
        GameSubmission: {
            /** Token */
            token: string;
            result: components["schemas"]["GameResultBody"];
        };
        /**
         * GateId
         * @enum {string}
         */
        GateId: "activation" | "checkpoint_1" | "checkpoint_2";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Role */
            role: string;
        };
        /** OperatorState */
        OperatorState: {
            /** Live Forced */
            live_forced: boolean;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /** ProfileView */
        ProfileView: {
            /** Recipient */
            recipient: string;
            /** Difficulty */
            difficulty: string | null;
            /** Phase */
            phase: string;
            /** Segment */
            segment: number;
            /** Total Segments */
            total_segments: number;
            /** Cleared */
            cleared: number;
            /** Lives */
            lives: number | null;
            /** Started At */
            started_at: string;
            /** Answered */
            answered: components["schemas"]["AnsweredView"][];
            /** Trophies */
            trophies: string[];
        };
        /** QuestionView */
        QuestionView: {
            /** Prompt */
            prompt: string;
            /** Blank */
            blank: string;
        };
        /** ResetRunRequest */
        ResetRunRequest: {
            /** Run Id */
            run_id: number;
            /** Confirm */
            confirm: string;
        };
        /** ResetRunResponse */
        ResetRunResponse: {
            /** Run Id */
            run_id: number;
            /** Deleted */
            deleted: {
                [key: string]: number;
            };
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: number;
            /** Difficulty */
            difficulty: string | null;
            /** Phase */
            phase: string;
            /** Segment */
            segment: number;
            /** Cleared Segments */
            cleared_segments: number[];
            /** Released Rewards */
            released_rewards: number[];
            /** Lives */
            lives: number | null;
            /** Trophies */
            trophies: string[];
        };
        /** RunView */
        RunView: {
            /** Phase */
            phase: string;
            /** Segment */
            segment: number;
            /** Difficulty */
            difficulty: string | null;
            /** Cleared Segments */
            cleared_segments: number[];
            /** Released Rewards */
            released_rewards: number[];
            /** Lives */
            lives: number | null;
            /** Question Attempts Left */
            question_attempts_left: number | null;
            /** Trophies */
            trophies: string[];
            question: components["schemas"]["QuestionView"] | null;
        };
        /** SegmentBriefView */
        SegmentBriefView: {
            /** Segment */
            segment: number;
            /** Token */
            token: string;
            /** Seed */
            seed: string;
            /** Mechanic */
            mechanic: string;
            /** Params */
            params: {
                [key: string]: number;
            };
        };
        /** SessionInfo */
        SessionInfo: {
            /** Authenticated */
            authenticated: boolean;
            /** Role */
            role: string | null;
            /** Live */
            live: boolean;
            /** Seconds Until Live */
            seconds_until_live: number;
        };
        /** SkipGameRequest */
        SkipGameRequest: {
            /** Run Id */
            run_id: number;
        };
        /** SkipGameResponse */
        SkipGameResponse: {
            /** Phase */
            phase: string;
            /** Segment */
            segment: number;
        };
        /** ToastRequest */
        ToastRequest: {
            /** Run Id */
            run_id: number;
            /** Text */
            text: string;
        };
        /** TrophyView */
        TrophyView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Grade */
            grade: string;
            /** Hidden */
            hidden: boolean;
        };
        /** UnlockGateRequest */
        UnlockGateRequest: {
            /** Run Id */
            run_id: number;
            gate: components["schemas"]["GateId"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    session_info_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    content_api_content_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentView"];
                };
            };
        };
    };
    read_run_api_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
        };
    };
    profile_api_run_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
        };
    };
    run_profile_chosen_api_run_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
        };
    };
    activate_api_run_activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_installed_api_run_installed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
        };
    };
    run_howto_acked_api_run_howto_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
        };
    };
    choose_difficulty_api_run_difficulty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DifficultyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_segment_api_run_segment_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentBriefView"];
                };
            };
        };
    };
    submit_game_api_run_segment_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_run_segment_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checkpoint_api_run_checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_release_api_operator_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeReleasedMsg"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_toast_api_operator_toast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_gate_api_operator_unlock_gate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnlockGateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bypass_checkpoint_api_operator_pass_checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BypassCheckpointRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BypassCheckpointResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_game_api_operator_skip_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkipGameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_run_api_operator_reset_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_golive_api_operator_force_golive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    operator_state_api_operator_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorState"];
                };
            };
        };
    };
}
